env:
  - GHCVER=7.4.1
  - GHCVER=7.4.2
  - GHCVER=7.6.3
  - GHCVER=7.8.3

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install libgtksourceview-3.0-dev libwebkitgtk-3.0-dev
  - sudo apt-get install cabal-install-1.20 ghc-$GHCVER
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.20/bin:$PATH
  - cabal update
  - |
    if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ]; then
      sudo apt-get install happy-1.19.3 alex-3.1.3
      export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.3/bin:$PATH
    else
      sudo apt-get install happy alex
    fi

install:
  - cabal install Cabal
  - cabal install gtk2hs-buildtools
  - cabal install ./ vendor/ltk vendor/leksah-server vendor/haskellVCSWrapper/vcswrapper vendor/haskellVCSGUI/vcsgui --enable-tests --only-dependencies
  - cabal install vendor/ltk vendor/leksah-server vendor/haskellVCSWrapper/vcswrapper vendor/haskellVCSGUI/vcsgui

script:
  - cabal configure --enable-tests -v2
  - cabal build
  - cabal test
  - cabal sdist

notifications:
  irc:
    channels: "irc.freenode.net#leksah"
  email: true
